### ISSUE TITLE
New 2019.1

### ISSUE THREAD

**Issue by lzysuqianqiu** [necan/RedisDesktopManager-Windows#9]

**Comment by XiaoBingBy** [comment]
+1

**Comment by st7yws** [comment]
+1

**Comment by imyip** [comment]
以为尝试着在 1903 的 sandbox 尝试编译 ,居然sandbox安装不了软件 .....

**Comment by wwwwei0** [comment]
> 以为尝试着在 1903 的 sandbox 尝试编译 ,居然sandbox安装不了软件 .....

需要梯子，否则下载不动

**Comment by imyip** [comment]
> > 以为尝试着在 1903 的 sandbox 尝试编译 ,居然sandbox安装不了软件 .....
> 
> 需要梯子，否则下载不动

下载好办 ,就是在 sandbox 里面 vscode 都安装不了 ,然后就没深究了

**Comment by hrj5032188** [comment]
编译 libssh2 的第一步走不下去
3rdparty/qredisclient/3rdparty目录下已经没有qsshclient文件夹了

**Comment by xyhere2001** [comment]
作者请看到 +1

**Comment by x5zj** [comment]
2019.1 请编译一下好吗？没这个环境。谢谢

**Comment by yuanrui** [comment]
+1
